# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'UserListDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UserListDemo

  # ui
  pod 'Kingfisher', '~> 5.0'

  # rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 5.2'

end
